# Generated by Django 4.2.20 on 2025-04-21 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todoitem",
            name="created_at",
        ),
        migrations.AddField(
            model_name="todoitem",
            name="description",
            field=models.TextField(default="No description"),
        ),
        migrations.AlterField(
            model_name="todoitem",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
